name: '.NET dependabot bot'
description: Automatically keep dependabot.yml files updated.
author: 'David Pine'
branding:
  icon: shield
  color: blue
inputs:
  root-directory:
    description: 'The root directory in which to run the automated dependabot evaluation.'
    default: '/github/workspace'
  dependabot-yml-path:
    description: 'The system file path to the dependabot.yml file.'
    default: '.github/dependabot.yml'

runs:
  using: docker
  image: ./src/dependabot-bot/Dockerfile
  args:
    - ${{ inputs.root-directory }}
    - ${{ inputs.dependabot-yml-path }}
