name: Clean repo
description: Automatically clean up unused files and replace links in a DocFx repo.
author: Genevieve Warren
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'sliders'
  color: 'purple'
inputs:
  start-directory:
    description: 'Top-level directory in which to perform clean up (for example, find orphaned markdown files).'
    required: true
  docset-root:
    description: 'The full path to the root directory for the docset, e.g. "./dotnet-docs/docs".'
    default: './docs'
  repo-root:
    description: 'The full path to the local root directory for the repository, e.g. "dotnet-docs"'
    default: '.'
  delete:
    description: 'True to delete orphaned files.'
    default: 'false'
  orphaned-topics:
    description: 'Use this option to find orphaned topics.'
    default: 'false'
  orphaned-images:
    description: 'Find orphaned .png, .gif, .jpg, or .svg files.'
    default: 'false'
  catalog-images:
    description: 'Map images to the markdown/YAML files that reference them.'
    default: 'false'
  orphaned-snippets:
    description: 'Find orphaned .cs and .vb files.'
    default: 'false'
  orphaned-includes:
    description: 'Find orphaned INCLUDE files.'
    default: 'false'
  lookback-days:
    description: 'The number of days to check for link-click activity.'
    default: '180'
  output-file:
    description: 'The file to write the redirect page view output to.'
  replace-redirects:
    description: 'Find backlinks to redirected files and replace with new target.'
    default: 'false'
  relative-links:
    description: 'Replace site-relative links with file-relative links.'
    default: 'false'
  remove-hops:
    description: 'Clean redirection JSON file by replacing targets that are themselves redirected (daisy chains).'
    default: 'false'
runs:
  using: docker
  image: Dockerfile
  args:
    - '--start-directory'
    - ${{ inputs.start-directory }}
    - '--docset-root'
    - ${{ inputs.docset-root }}
    - '--repo-root'
    - ${{ inputs.repo-root }}
    - '--delete'
    - ${{ inputs.delete }}
    - '--orphaned-topics'
    - ${{ inputs.orphaned-topics }}
    - '--orphaned-images'
    - ${{ inputs.orphaned-images }}
    - '--catalog-images'
    - ${{ inputs.catalog-images }}
    - '--orphaned-snippets'
    - ${{ inputs.orphaned-snippets }} 
    - '--orphaned-includes'
    - ${{ inputs.orphaned-includes }}
    - '--lookback-days'
    - ${{ inputs.lookback-days }}
    - '--output-file'
    - ${{ inputs.output-file }}
    - '--replace-redirects'
    - ${{ inputs.replace-redirects }}
    - '--relative-links'
    - ${{ inputs.relative-links }}
    - '--remove-hops'
    - ${{ inputs.remove-hops }}